### ISSUE TITLE
make docker ssh key generation more robust

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1000]
Bug report:

Hi, when I updated the images, I could run and access sagemathcloud by localhost:8080 , but after I restarted my computer and re-ran command sudo docker start smc, I can't access it. I use sudo docker logs smc and get the following information:
```
Generating public/private rsa key pair.
/root/.ssh/id_rsa already exists.
Overwrite (y/n)? chdir /smc/src
. smc-env; sage -pip install --upgrade smc_sagews/
echo "install_scripts('/usr/local/bin/')" | sage
service haproxy start
service nginx start
service rethinkdb start
service ssh start
ssh-keygen -b 2048 -N '' -f /root/.ssh/id_rsa
Traceback (most recent call last):
  File "./run.py", line 157, in <module>
    main()
  File "./run.py", line 148, in main
    root_ssh_keys()
  File "./run.py", line 77, in root_ssh_keys
    run("ssh-keygen -b 2048 -N '' -f /root/.ssh/id_rsa")
  File "./run.py", line 37, in run
    raise RuntimeError("error running '{cmd}'".format(cmd=cmd))
RuntimeError: error running 'ssh-keygen -b 2048 -N '' -f /root/.ssh/id_rsa'
```

Probably adding `rm /root/.ssh/id_rsa' somewhere would fix this easily.

**Comment by williamstein** [comment]
I'm working on this... testing another build right now.
