### ISSUE TITLE
make local hub read/write file lock have a timeout

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1147]
For the first time I just got this error message (in browser) while opening a file: "file is currently being read or written":

<img width="350" alt="screen shot 2016-10-27 at 5 58 15 am" src="https://cloud.githubusercontent.com/assets/1276278/19768003/62b4f960-9c0a-11e6-8052-3fd015f03d4a.png">

Consulting the log around now shows this:

```
2016-10-27T12:19:42.171Z - debug: BUG ****************************************************************************
2016-10-27T12:19:42.177Z - debug: Uncaught exception: Error: write EPIPE
2016-10-27T12:19:42.291Z - debug: Error: write EPIPE
  at exports._errnoException (util.js:893:11)
  at WriteWrap.afterWrite (net.js:783:14)

2016-10-27T12:19:42.291Z - debug: BUG ****************************************************************************
Trace
  at process.<anonymous> (/usr/lib/node_modules/smc-project/local_hub.coffee:293:17)
  at emitOne (events.js:90:13)
  at process.emit (events.js:182:7)
  at process._fatalException (node.js:237:26)

2016-10-27T12:20:02.930Z - debug: received new connection
```

The relevant code is `src/smc-project/client.coffee`, where `write_file` and `path_read` both have a lock.  Assuming the async callback chain goes through fine, the lock is always removed.  However, I think if an exception were to get raised in the middle of that callback chain, then the lock would definitely stay forever.

Easy fix: make the lock a timestamp, and have it also expire after 15s say (as any read/write would finish that quickly).  Then even if an exception as above were to ever happen (due to a bug or anything else), we're good.

**Comment by williamstein** [comment]
Interestingly, SMC did -- as a result -- delete the contents of the file.

**Comment by haraldschilly** [comment]
today, I saw this again for a jupyter2 ipynb file. interestingly it didn't went away after one or two minutes. maybe there is an exception and triggering this over and over again? however, what I did was to restart the local hub in the project and then it showed up properly.

(I'm opening this in case you want to think about it)

**Comment by williamstein** [comment]
I implemented a debouncing for the file watcher, which should address the root cause.
