### ISSUE TITLE
smc_pyutil: using python2-nosite to avoid interferences with ~/.local

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1216]
See https://github.com/sagemathinc/smc/pull/1214

**Comment by haraldschilly** [comment]
```
pgrep -u 236465941
Project(project_id=eaa9ef8a-5e43-414a-aaa7-dbbdacedcda3).killall(...): kill attempt left 0 procs
/usr/sbin/userdel eaa9ef8a5e43414aaaa7dbbdacedcda3
/usr/sbin/groupdel eaa9ef8a5e43414aaaa7dbbdacedcda3
Traceback (most recent call last):
  File "/usr/local/bin/smc-compute", line 11, in <module>
    load_entry_point('smc-pyutil==1.1', 'console_scripts', 'smc-compute')()
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1030, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 900, in g
    result = getattr(Project(project_id=project_id, dev=args.dev, projects=args.projects, single=args.single), function)(**kwds)
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 442, in restart
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 434, in stop
    self.delete_user()
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 198, in delete_user
    c = open("/etc/cgrules.conf").read()
IOError: [Errno 13] Permission denied: '/etc/cgrules.conf'
```

**Comment by haraldschilly** [comment]
ok, that's fixed
