### ISSUE TITLE
sagews executor parser stumbles over multiple decorators

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1735]
The following is valid python, but it's not parsed correctly. That's why I classify this as a blocker.

```
def dummy(f):
    return f
```
```
@dummy
@dummy
def f(x):
    return 2*x+1
```
```
Error in lines 1-1
Traceback (most recent call last):
  File "/projects/sage/sage-7.5/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 982, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "<string>", line 1
    @dummy
         ^
SyntaxError: unexpected EOF while parsing
```

expected: `f(2)` → 5

**Comment by haraldschilly** [comment]
fix deployed and verified

**Comment by DrXyzzy** [comment]
ccelapsed: 1 hour
