### ISSUE TITLE
sagews error on `for x in [u"ááá", "ááá"]: print(x)`

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#1865]
This line causes an error in sagews but not in .term with command line sage, python, or python3:
```
for x in [u"ááá", "ááá"]: print(x)
```

Error output in sagews:
```
ááá
Error in lines 1-1
Traceback (most recent call last):
  File "/projects/sage/sage-7.5/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 989, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/projects/sage/sage-7.5/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 403, in write
    self._buf += output.replace('\x00','')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
*** WARNING: Code contains non-ascii characters ***
```

Non-error output from command line:
```
ááá
ááá
```

**Comment by haraldschilly** [comment]
works in prod, very good
