### ISSUE TITLE
console broken in local laptop development

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#246]
when I try to start a console on my laptop, I get this in 
`./src/data/projects/xx-xx-xx-xx/.smc/console_server/`
in revision 495057a24c349146

```
$ cat console_server.log
info: listening on port 59513
info: start_session {"event":"connect_to_session","id":"3d0c4091-c980-4309-98e9-00debd7da666","type":"console","project_id":"72e3bc19-dc25-404d-b74a-0e3a9dc583f1","session_uuid":"0fc1434e-7ebe-44fe-956e-5f5a9296f614","params":{"command":"bash","path":"./","filename":"terminal.term"}}
Error: Cannot find module '../build/Release/pty.node'
  at Function.Module._resolveFilename (module.js:337:15)
  at Function.Module._load (module.js:287:25)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/home/harri/p/smc-in-smc/src/smc-project/node_modules/pty.js/lib/pty.js:9:11)
  at Module._compile (module.js:425:26)
  at Object.Module._extensions..js (module.js:432:10)
  at Module.load (/home/harri/p/smc-in-smc/src/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/home/harri/p/smc-in-smc/src/smc-project/node_modules/pty.js/index.js:2:18)
  at Module._compile (module.js:425:26)
  at Object.Module._extensions..js (module.js:432:10)
  at Module.load (/home/harri/p/smc-in-smc/src/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/home/harri/p/smc-in-smc/src/smc-project/console_server_child.coffee:23:12)
  at Object.<anonymous> (/home/harri/p/smc-in-smc/src/smc-project/console_server_child.coffee:23:1)
  at Module._compile (module.js:425:26)
  at Object.exports.run (/home/harri/p/smc-in-smc/src/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/home/harri/p/smc-in-smc/src/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/home/harri/p/smc-in-smc/src/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/home/harri/p/smc-in-smc/src/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/home/harri/p/smc-in-smc/src/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:425:26)
  at Object.Module._extensions..js (module.js:432:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:457:10)
  at startup (node.js:136:18)
  at node.js:972:3
```

**Comment by williamstein** [comment]
The error is `Error: Cannot find module '../build/Release/pty.node'` which I think means pty.js isn't installed. What happens if you do `npm install` in the smc-project directory?
