### ISSUE TITLE
make a certain mkdir more robust to the potential that the directory already exists

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#254]
Reported by: Rob Beezer

> Collected 8 student projects, for the first time (for that assignment).  Two needed to be "re-collected"  due to errors (below).  Second attempts were successful, so there is no problem here. -- Rob
> 
> ```
> copy from student: Project(project_id=d0bd11cd-7c09-438c-af0e-f0b761952669).mkdir(...): ensuring path 2015-Fall/Math433-collect/Math433F15/Chapter08 exists
> Project(project_id=d0bd11cd-7c09-438c-af0e-f0b761952669).makedirs(...): creating /projects/d0bd11cd-7c09-438c-af0e-f0b761952669/2015-Fall/Math433-collect/Math433F15/Chapter08
> Traceback (most recent call last):
>   File "/usr/local/bin/smc-compute", line 9, in <module>
>     load_entry_point('smc-pyutil==1.0', 'console_scripts', 'smc-compute')()
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1896, in main
>     args.func(args)
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1672, in g
>     result = getattr(Project(project_id=project_id, btrfs=args.btrfs, bucket=args.bucket, storage=args.storage, archive=args.archive), function)(**kwds)
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1238, in mkdir
>     self.makedirs(abspath)
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1227, in makedirs
>     makedirs(path)
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1225, in makedirs
>     os.mkdir(name, 0700)
> OSError: [Errno 17] File exists: '/projects/d0bd11cd-7c09-438c-af0e-f0b761952669/2015-Fall/Math433-collect/Math433F15/Chapter08'
> copy from student: Project(project_id=d0bd11cd-7c09-438c-af0e-f0b761952669).mkdir(...): ensuring path 2015-Fall/Math433-collect/Math433F15/Chapter08 exists
> Project(project_id=d0bd11cd-7c09-438c-af0e-f0b761952669).makedirs(...): creating /projects/d0bd11cd-7c09-438c-af0e-f0b761952669/2015-Fall/Math433-collect/Math433F15/Chapter08
> Traceback (most recent call last):
>   File "/usr/local/bin/smc-compute", line 9, in <module>
>     load_entry_point('smc-pyutil==1.0', 'console_scripts', 'smc-compute')()
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1896, in main
>     args.func(args)
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1672, in g
>     result = getattr(Project(project_id=project_id, btrfs=args.btrfs, bucket=args.bucket, storage=args.storage, archive=args.archive), function)(**kwds)
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1238, in mkdir
>     self.makedirs(abspath)
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1227, in makedirs
>     makedirs(path)
>   File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/smc_compute.py", line 1225, in makedirs
>     os.mkdir(name, 0700)
> OSError: [Errno 17] File exists: '/projects/d0bd11cd-7c09-438c-af0e-f0b761952669/2015-Fall/Math433-collect/Math433F15/Chapter08'
> ```

**Comment by williamstein** [comment]
Probably already fixed.
