### ISSUE TITLE
cannot run: coffee> db=require('rethink').rethinkdb()

### ISSUE THREAD

**Issue by dwintergruen** [sagemathinc/smc#403]
I have followed the instructions  in install.MD

repl:3
_ = db = require('rethink').rethinkdb();
                            ^
TypeError: require(...).rethinkdb is not a function
  at repl:3:29
  at Object.exports.runInThisContext (vm.js:54:17)
  at runInContext (/home/salvus/smc/src/node_modules/coffee-script/lib/coffee-script/repl.js:57:17)
  at REPLServer.replDefaults.eval (/home/salvus/smc/src/node_modules/coffee-script/lib/coffee-script/repl.js:46:25)
  at bound (domain.js:287:14)
  at REPLServer.runBound [as eval] (domain.js:300:12)
  at repl.js:417:12
  at REPLServer.<anonymous> (/home/salvus/smc/src/node_modules/coffee-script/lib/coffee-script/repl.js:86:9)
  at emitOne (events.js:95:20)
  at REPLServer.emit (events.js:182:7)
  at REPLServer.Interface._onLine (readline.js:211:10)
  at REPLServer.Interface._line (readline.js:550:8)
  at REPLServer.Interface._ttyWrite (readline.js:827:14)
  at ReadStream.onkeypress (readline.js:106:10)
  at emitTwo (events.js:105:20)
  at ReadStream.emit (events.js:185:7)
  at emitKeys (readline.js:1251:14)
  at [object Generator].next (native)
  at ReadStream.onData (readline.js:919:36)
  at emitOne (events.js:90:13)
  at ReadStream.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:147:16)
  at ReadStream.Readable.push (_stream_readable.js:111:10)
  at TTY.onread (net.js:523:20)

If I start the hub I also get the error that the db "SMC" doesn't exist.

**Comment by dwintergruen** [comment]
Got it has to be:
 db=require('smc-hub/rethink').rethinkdb();
