### ISSUE TITLE
frobby raises OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by eulerreich** [sagemathinc/smc#491]
I ran the following in a sage worksheet
```python
rr = QQ['x0, x1, x2, x3, x4, x5, x6, x7']
rr.inject_variables()
I = rr.ideal (x1*x2*x7, x6*x7, x1*x4*x7, x0*x2*x4*x6, x0*x3*x5, x2*x3, x0*x1, x3*x5*x6, x4*x5)
frobby.hilbert(I)
```
and got this error

```
Error in lines 4-4
Traceback (most recent call last):
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 904, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/sage/interfaces/frobby.py", line 160, in hilbert
    frobby_output = self('hilbert', input=frobby_input)
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/sage/interfaces/frobby.py", line 77, in __call__
    process = Popen(command, stdin = PIPE, stdout = PIPE, stderr = PIPE)
  File "/projects/sage/sage-6.10/local/lib/python/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/projects/sage/sage-6.10/local/lib/python/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by williamstein** [comment]
Still broken:

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-22-164759-issue-491.sagews

**Comment by williamstein** [comment]
Low priority since very few users of frobby...

**Comment by williamstein** [comment]
Heh wait, this is really easy to solve since it's just complaining that frobby isn't installed, and Frobby is evidently just **in Ubuntu**, surprisingly:

    sudo apt-get install  frobby
