### ISSUE TITLE
some worksheet markdown crashes smc-sagews2pdf

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#506]
There is a sage worksheet (which is private and I've put it here for SMC devs):

https://cloud.sagemath.com/projects/369491f1-9b8a-431c-8cd0-150dd15f7b11/files/private/tests/2016-04-14-142856-bad-print-worksheet.sagews

such that 

```
~/private/tests$ smc-sagews2pdf 2016-04-14-142856-bad-print-worksheet.sagews
converting: 2016-04-14-142856-bad-print-worksheet.sagews --> 2016-04-14-142856-bad-print-worksheet.pdf
Traceback (most recent call last):
  File "/usr/local/bin/smc-sagews2pdf", line 9, in <module>
    load_entry_point('smc-pyutil==1.0', 'console_scripts', 'smc-sagews2pdf')()
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/sagews2pdf.py", line 657, in main
    style=args.style
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/sagews2pdf.py", line 612, in sagews_to_pdf
    style=style)
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/sagews2pdf.py", line 576, in latex
    t, cmd = c.latex()
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/sagews2pdf.py", line 422, in latex
    return self.latex_input() + self.latex_output(), self._commands
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/sagews2pdf.py", line 447, in latex_output
    s += md2tex(x['md'], self._commands)
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/sagews2pdf.py", line 378, in md2tex
    y = html2tex(x, cmds)
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/sagews2pdf.py", line 362, in html2tex
    return reconstruct_math(parser.result, tmp)
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/sagews2pdf.py", line 338, in reconstruct_math
    s = reconstructMath(s, tmp[-1][0][1], equation_delims=tmp[-1][1])
  File "/usr/local/lib/python2.7/dist-packages/smc_pyutil/markdown2Mathjax.py", line 138, in reconstructMath
    raise ValueError("More codeblocks given than valid placeholders in text.")
ValueError: More codeblocks given than valid placeholders in text.
```

Also, in the UI, clicking print seems to work and gives a link to a file, which is never created.  So there are two issues here: (1) why does the markdown in that worksheet cause a traceback?  (2) why does the SMC UI not say "heh, printing failed"?

**Comment by haraldschilly** [comment]
I boiled this down exactly this example, in one sagews cell:

    %md
    <div style="";></div> $x$

note, the wrong html and the immediately following formula. the stracktrace suggests, that the formula parsing is not working, but no idea why this html before it causes this …
