### ISSUE TITLE
[CRITICAL] default sage startup is messed up on all machines for some reason

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#719]
Start "sage" in a terminal in any project anywhere, and get:
```
~$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath Version 6.10, Release Date: 2015-12-18                    │
│ Enhanced for SageMathCloud.                                        │
└────────────────────────────────────────────────────────────────────┘
/projects/sage/sage-6.10/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:440: UserWarning: As of IPython 5.0 `Prom
ptManager` config will have no effect and has been replaced by TerminalInteractiveShell.prompts_class
  warn('As of IPython 5.0 `PromptManager` config will have no effect'
[SageTerminalApp] WARNING | Error in loading extension: line_profiler
Check your config files in /projects/c8ef2449-eff9-45e2-aeb1-e4a5a05bb188/.sage/ipython_genutils-0.1.0/profile_default
Traceback (most recent call last):
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/IPython/core/shellapp.py", line 246, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/IPython/core/extensions.py", line 85, in load_extension
    if self._call_load_ipython_extension(mod):
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/IPython/core/extensions.py", line 132, in _call_load_ipython_exten
sion
    mod.load_ipython_extension(self.shell)
  File "/projects/sage/sage-6.10/local/lib/python2.7/site-packages/line_profiler.py", line 372, in load_ipython_extension
    ip.define_magic('lprun', magic_lprun)
AttributeError: 'SageTerminalInteractiveShell' object has no attribute 'define_magic'
In [1]:  
```

My guess is that IPython got upgraded by @haraldschilly somehow, and isn't compatible with Sage version 6.10.  Fix: reinstall version of IPython that comes with Sage.

**Comment by haraldschilly** [comment]
Fixed, and I honestly don't really remember how this did happen … so far, such ipython upgrades probably got unnoticed because 5.0 wasn't available.
