### ISSUE TITLE
parse_bup_timestamp fails on OS X

### ISSUE THREAD

**Issue by edgarcosta** [sagemathinc/smc#765]
Hello,

I was trying to install smc on my desktop,  and one of the tests regarding timestamps failed.

Best,
Edgar

```
  $ npm test

> sagemathcloud@1.0.0 test /Users/edgarcosta/Applications/smc/src
> export SMC_TEST=true&& cd smc-util && npm test && cd ../smc-util-node && npm test && cd ../smc-hub && npm test && cd ../smc-webapp && npm test


> smc-util@1.0.0 test /Users/edgarcosta/Applications/smc/src/smc-util
> SMC_TEST=true node_modules/.bin/mocha --reporter progress


  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  187 passing (849ms)
  1 failing

  1) parse_bup_timestamp reads e.g. 2014-01-02-031508 and returns a date object:

      AssertionError: expected 2014-01-01 22:15:08.000 -0500 to equal 2014-01-02 03:15:08.000 -0500
      + expected - actual

      -[Date: 2014-01-02T03:15:08.000Z]
      +[Date: 2014-01-02T08:15:08.000Z]
      
    at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
    at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
    at Context.<anonymous> (test/misc-test.coffee:851:23)
  



npm ERR! Test failed.  See above for more details.
npm ERR! Test failed.  See above for more details.
```

**Comment by williamstein** [comment]
In SMC we assume the server's timezone is UTC.

**Comment by edgarcosta** [comment]
Thank you. 

Perhaps would be useful in the future to write down that assumption.

**Comment by williamstein** [comment]
I'm going re-open this.  The fix will be to clearly document that assumption, including make it in the error message, **or** to remove that assumption (at least for local use)...
