### ISSUE TITLE
install processing/.js and calysto for jupyter

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#900]
1. [ ] install processing globally
1. [ ] install [calysto](https://github.com/Calysto/calysto_processing)

**Comment by haraldschilly** [comment]
installing processing globally is easy, i.e. I extracted the tarball and placed it into /opt/processing/[symlink "current" → "processing-x.y.z"]/...

calysto fails, even when I'm not updating dependencies (also failes with updating python deps)

```
Traceback (most recent call last):
  File "/projects/sage/sage-7.3/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/projects/sage/sage-7.3/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/projects/20e4a191-73ea-4921-80e9-0a5d792fc511/.local/lib/python2.7/site-packages/metakernel/_metakernel.py", line 362, in do_execute
    retval = self.do_execute_direct(code)
  File "/projects/20e4a191-73ea-4921-80e9-0a5d792fc511/.local/lib/python2.7/site-packages/calysto_processing/kernel.py", line 153, in do_execute_direct
    stdout, stderr = [str(bin, encoding="utf-8") for bin in p.communicate()]
TypeError: str() takes at most 1 argument (2 given)
```
